name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      # Fail fast is disabled because there are Go version specific features and tests
      # that should be able to fail independently.
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.14', '1.15', '1.16', '1.17']
        tags: ['']
    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -race -tags '${{ matrix.tags }}' -v ./...
        if: runner.os != 'Windows'

      - name: Test (without race detector)
        run: go test -tags '${{ matrix.tags }}' -v ./...
        if: runner.os == 'Windows'
